let plants = [{
  id: 1,
  name: '西红柿',
  speed: 5000,
  cost: 10,
  profit: 20,
  unlockPrice: 100,
  state: 1,
  grows: 'spring',
  image: 'xihongshi.png',
  totalGrown: 0
}, {
  id: 2,
  name: '小麦',
  speed: 1000, // 成长速度
  cost: 0, // 成本价格
  profit: 1, // 利润
  state: 0, // 0为解锁，1为未解锁
  grows: 'summer',
  image: 'xiaomai.png',
  totalGrown: 0
}, {
  id: 3,
  name: '萝卜',
  speed: 3000,
  cost: 50,
  profit: 200,
  state: 1,
  unlockPrice: 200,
  grows: 'autumn',
  image: 'luobo.png',
  totalGrown: 0
}, {
  id: 4,
  name: '白菜',
  speed: 6000,
  cost: 1000,
  profit: 3500,
  state: 1,
  unlockPrice: 5e+3,
  grows: 'winter',
  image: 'baicai.png',
  totalGrown: 0
}, {
  id: 5,
  name: '土豆',
  speed: 10000,
  cost: 10000,
  profit: 40000,
  unlockPrice: 7e+4,
  state: 1,
  grows: 'autumn',
  image: 'tudou.png',
  totalGrown: 0
}, {
  id: 6,
  name: '豌豆',
  speed: 11000,
  cost: 1e+5,
  profit: 5.5e+5,
  unlockPrice: 10e+4,
  state: 1,
  grows: 'spring',
  image: 'wandou.png',
  totalGrown: 0
}, {
  id: 7,
  name: '甘蔗',
  speed: 12000,
  cost: 20e+5,
  profit: 80e+5,
  unlockPrice: 2e+5,
  state: 1,
  grows: 'summer',
  image: 'ganzhe.png',
  totalGrown: 0
}, {
  id: 8,
  name: '青椒',
  speed: 13000,
  cost: 3e+7,
  profit: 9e+7,
  unlockPrice: 6e+5,
  state: 1,
  grows: 'winter',
  image: 'qingjiao.png',
  totalGrown: 0
}]

export default plants
